[parity]
chain = "dev"
base_path = "db.ss"

[ui]
disable = true

[rpc]
disable = true

[ipc]
disable = true

[dapps]
disable = true

[websockets]
disable = true

[network]
port = 30301
bootnodes = []

[ipfs]
enable = false

[snapshots]
disable_periodic = true

[secretstore]
#self_secret = "PUT YOUR ACCOUNT ADDRESS HERE AND UNCOMMENT THIS LINE" # account address without the "0x"
disable = false
disable_http = false
http_interface = "local"
http_port = 8010
acl_contract = "none"
server_set_contract = "none"
nodes = []
interface = "local"
port = 8011
path = "db.ss/secretstore"

[account]
#password = ["integration_tests/configs/ss.pwd"] # UNCOMMENT THIS LINE AFTER FILLING IN ss.pwd
