# File users.toml
# This configuration file can be used for either Alice, Bob or Charlie

[parity]
chain = "dev"
base_path = "db.users"

[rpc]
port = 8545 #default http port for RPC
apis = ["secretstore","eth","net","personal"] # to access dedicated methods

[secretstore]
disable = true # users do not run a secret store node

[network]
port = 30300
bootnodes = [
  # INSERT YOUR SECRET STORE PUBLIC NODE URL HERE
]
